/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Numbers n = new Numbers(100);
        n.fillNumbers(0, 1000);
        n.fillNumbers2();
        System.out.println(n);
    }
}
